### ISSUE TITLE
Odevzdávám DU k lekci 7

### ISSUE THREAD

**Issue by JarmilaKo** [JarmilaKo/Domaci_ukoly#1]
Ahoj @pesikj,
posílám úkoly ze sedmé lekce. Jarmila

**Comment by pesikj** [comment]
Ahoj Jarmilo,
nevím, co přesně myslíš u toho displot, ale přidání hustoty rozdělení bohužel nepodporuje. Burr rozdělení jsem neznal :-)

U druhého cvičení je super ten bodový graf, kde máš krásně ukázáno, že ta jedna ryba je jiná.

Jirka

**Comment by pesikj** [comment]
Můžeš uzavřít toto issue.
