### ISSUE TITLE
DU - lekce 8

### ISSUE THREAD

**Issue by JarmilaKo** [JarmilaKo/Domaci_ukoly#2]
Ahoj @pesikj,
posílám úkoly ze sedmé lekce. Jarmila

**Comment by JarmilaKo** [comment]
Ahoj @pesikj,
neměla jsem na mysli sedmou, ale osmou lekci a teď už je tam i devátá. J.

**Comment by pesikj** [comment]
Ahoj, osmá lekce je v pohodě :-)

**Comment by pesikj** [comment]
9. lekce taky, jen nerozumím komentáři o f1 score, to vidím, že je vždy dan 85 % (i pro 13 sousedů).

**Comment by pesikj** [comment]
Jinak můžeš uzavřít toto issue. :-)
