### ISSUE TITLE
ukoly: Lekce 10

### ISSUE THREAD

**Issue by JarmilaKo** [JarmilaKo/Domaci_ukoly#3]
Ahoj @pesikj,
posílám úkoly z 10. lekce.
Děkuji za dnešní konzultaci. Bez ní bych je nedokázala dokončit.
Jarmila

**Comment by pesikj** [comment]
Ahoj Jarmilo,
u toho prvního zadání a posledního bodu to Lída myslela tak, že bys v modelu nechala jen tu nejdůležitější proměnnou. Ty jsi řešila opačný problém, zkusila jsi tu nejdůležitější vyřadit, ale to nevadí. Naopak je vidět, že bez té nejdůležitější se v modelu docela obejdeme. :-)

**Comment by pesikj** [comment]
Stačí případně upravit řádek 41 takto:
`X1 = data[["plant-stand"]]`

**Comment by pesikj** [comment]
Jinak super, připsal jsem ti 2 body, uzavři prosím issue :-)
